apiVersion : apps/v1
kind: Deployment
metadata:
  name: madhavigawaritetrisgame 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: madhavigawaritetrisgame
  template:
    metadata:
      labels:
        app: madhavigawaritetrisgame 
    spec:
      containers:
        - name: madhavigawaritetrisgame 
          image: mylabcr240145.azurecr.io/madhavigawaritetrisgame
          ports:
          - containerPort: 80